### PR TITLE
Hexaforce and pexod + udev

### PR DESCRIPTION
**Pull request by dogoepp**
Add configuration and description files for Hexaforce, our new hexapod. For convenience, udev rules were added to distinguish between the force sensors and USB to Dynamixel interface.

### CODE REVIEW

**Comment by dogoepp** [comment]
`hexapod_driver` has now gained a new driver, working in Cartesian domain, using [`hexapod_ik`](https://github.com/resibots/hexapod_ik).

**Review by costashatz — COMMENTED** [review]
This PR is very nice! Thanks for the effort!

One minor comment:

We could make the cartesian controller optional. In particular, if trak_ik_lib is not found we should not build it. It's not good to enforce this dependency (we might not use it in the end). @jbmouret  @dogoepp  what do you think?

**Comment by dogoepp** [comment]
You are very right. This should be an optional dependency.

**Comment by costashatz** [comment]
We should also fix the conflicts...

**Comment by dogoepp** [comment]
I can handle the conflicts. Do you feel comfortable with the CMakeLists ?

**Comment by costashatz** [comment]
> I can handle the conflicts. Do you feel comfortable with the CMakeLists ?

I am a very comfortable guy :stuck_out_tongue: . Yes, I will try to fix it once you're done with the conflicts!

**Comment by dogoepp** [comment]
The conflicts have been resolved in #14 which we should be using now. I close this PR.

**Pull request closed without merging**
